// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrrptcpvncoqfpvktsnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycnB0Y3B2bmNvcWZwdmt0c25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDg1MjEsImV4cCI6MjA2MDEyNDUyMX0.QeJ-7Wx4mg_qVMt2Edg_D6nYxi1ex1X9-0DshxrTLVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);